### ISSUE TITLE
Add support for integration with IPython's "autoawait" feature

### ISSUE THREAD

**Issue by wimiko** [cocotb/cocotb#1081]
At the moment, it is not possible to run cocotb coroutines from an IPython shell. 
IPython is able to run asynchronous code (see https://ipython.readthedocs.io/en/stable/interactive/autoawait.html), but support for this has to be added to the scheduler.

**Comment by ktbarrett** [comment]
Should this a scheduler "feature", or could we come up with something cleaner?

We could modify cocotb's start up so that once loaded cocotb will jump to a user specified entry point (we already do this sort of by passing cocotb the test module), which could be the regression manager, or could be IPython, or whatever. Ideally, the scheduler should be a stand-alone component: I should be able to use the scheduler in a purely Python environment. At that point, what we are trying to achieve is trivial.

Everything in cocotb is just too tightly coupled for my tastes.

**Comment by eric-wieser** [comment]
I think step 1 is decoupling the concept of tests (ie, the regression manager) from the scheduler. I made a start on simplifying the interface, but they're still couple's.

**Comment by eric-wieser** [comment]
Tried to make a start on this, but I can't work out how to set the hook:

https://gitter.im/ipython/ipython?at=5e8f21e09316f34b8d8ebed3

**Comment by eric-wieser** [comment]
Alright, I have this working!
