### ISSUE TITLE
Can cocotb use C++11?

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1087]
Might be good to have a minimum supported C++ standard version stated in our docs, just like we have a minimum supported python version.

**Comment by imphil** [comment]
More useful than language features is typically specifying the minimum supported compiler, *and* having a demonstrated need for a given feature from a language version.

Probably the most common Linux distribution in the EDA industry is RHEL, next to SLES and Ubuntu.

- RHEL7: GCC 4.8 (https://access.redhat.com/solutions/19458)
- RHEL6: GCC 4.4 (https://access.redhat.com/solutions/19458)

- Ubuntu 16.04: GCC 5.3.1
- Ubuntu 18.04: GCC 7.4.0

- SLES 12 SP3: GCC 4.8
(Documentation for SLES is as usual harder to find than for other distributions.)

For C++11, many things are already available in GCC 4.4, some are not ([docs](https://gcc.gnu.org/projects/cxx-status.html)). Would you be ok with specifying GCC 4.4 as minimum version for now, or do you have a specific feature you'd like to use which isn't available there?

**Comment by TC01** [comment]
Note that RHEL6 ships with python 2.6, which is too old to support cocotb anyway. To get python 2.7, you need to either build it yourself or enable a SCL. (I'm currently using cocotb on a RHEL6 server and have done exactly that).

So there is a potential argument to make for moving to gcc 4.8 instead of 4.4, if necessary: it already doesn't work out of the box due to the system Python version.

**Comment by themperek** [comment]
@TC01 You can use cond and install locally (https://conda.io/en/latest/)

**Comment by TC01** [comment]
Sure-- I would count that as "build it yourself" though. You're not getting the system Python.

It's also possible to get a newer gcc on RHEL6 (again, either by enabling a SCL or setting it up yourself).
