### ISSUE TITLE
Document cocotb module variables

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#1724]
The `cocotb` module has some important variables which aren't documented:

- [ ] SIM_NAME
- [ ] SIM_VERSION
- [ ] RANDOM_SEED
- [ ] log
- [X] scheduler
- [ ] regression_manager
- [X] plusargs
- [ ] argv/argc
- [ ] LANGUAGE

**Comment by cmarqu** [comment]
Some related notes:

https://docs.cocotb.org/en/latest/library_reference.html?highlight=plusargs#cocotb.plusargs should get a backreference to https://docs.cocotb.org/en/latest/building.html?highlight=plusargs#var-PLUSARGS

Same for ``RANDOM_SEED`` once we add a docstring (https://docs.cocotb.org/en/latest/building.html#envvar-RANDOM_SEED).

Also, ``plusargs`` should be moved out of the "Utilities" section.

What's up with the different cases? Should they all be lowercased, or ``plusargs`` uppercased since it also comes from an envvar? (But then, ``SIM_*``  do not come from envvars.)

**Comment by ktbarrett** [comment]
Yeah, it's not very apparent that they are there, so I guess people forget about them. We could provide aliases with a consistent casing? Not sure that's worth it though. I wonder if there is some better way to make that information available.
