### ISSUE TITLE
stale bot no longer closing stale issues?

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2353]
The action is running, but recently it's not been closing issues it has marked as stale (see dates on #2074). There are also questions not being marked as stale (#2051).

**Comment by ktbarrett** [comment]
Some discussion in https://github.com/actions/stale/issues/284. It *might* be fixed in the next release, but seeing as I don't get an error message, I'm not so sure that's the same issue.

**Comment by imphil** [comment]
ACTIONS_STEP_DEBUG=true is set as secret in the cocotb repository.

**Comment by C0ZEN** [comment]
Any update?

**Comment by ktbarrett** [comment]
Development is paused until we release (~1 week from now). I'll bump the `operations-per-run` and maybe remove the `close?` tag after that.

**Comment by C0ZEN** [comment]
You have this in your configuration `only-labels: type:question,status:close?`.
Are you aware that it's working only if both labels are on the issue/PR at the same time?
Also `operations-per-run: 5` should be set to `operations-per-run: 30` IMO so that you are sure to handle more issues and PR per run.
Lastly, the next stale release will include this https://github.com/actions/stale/issues/308 which will allow you to only handle issue/PR with either `type:question` or `status:close?` labels if set like this `any-of-labels: type:question,status:close?` instead of the current `only-labels` one.

**Comment by ktbarrett** [comment]
Ahh, I was not aware that `only-labels` was an intersection, it looks like the documentation was just updated to indicate that. I'll switch to `any-of-labels`. Also, [there is a duplicate](https://github.com/actions/stale/blame/main/README.md#L26-L27).

**Comment by C0ZEN** [comment]
@ktbarrett if you want to go ahead of schedule you can target the main branch nevertheless if you want to play it safe and let the new version be more tested in a real repository you can wait for the next release.
Nice catch regarding the documentation and it's already fixed here https://github.com/actions/stale/pull/341 😎
