### ISSUE TITLE
Attribute Error : Running test

### ISSUE THREAD

**Issue by Nimrod123** [cocotb/cocotb#2616]
Im currently making a testbench for sum of N 8 bit input module.
[sumofN.txt](https://github.com/cocotb/cocotb/files/6785503/sumofN.txt)
This is the testbench code
[SumN_tb.txt](https://github.com/cocotb/cocotb/files/6785479/SumN_tb.txt)
And this is the error which im getting when I try to run make
[cmd.log](https://github.com/cocotb/cocotb/files/6785489/cmd.log)
it occurs for all await statements (RunningTest object has no attribute error) . Im quite new with cocotb. If theres anyother mistakes, please do tell me 
Thanks in advance

**Comment by imphil** [comment]
You have this code in your testbench:

```python
class SumN_tb():
    async def reset(self):
        self.dut.RST_N.setimmediatevalue(0)
        self.dut.EN_in_put.setimmediatevalue(0)
        self.dut.in_put.setimmediatevalue(0)
        self.dut.EN_out_get.setimmediatevalue(0)
        self.dut.EN_configure.setimmediatevalue(0)
        self.dut.configure_address.setimmediatevalue(0)
        self.dut.configure_data.setimmediatevalue(0)
        await FallingEdge(self.dut.CLK)
        self.dut.RST_N <= 1

...

@cocotb.test()
async def SumN_tb(dut, N = 4, overflow_test = None, config_test = None):
    tb=SumN_tb(dut, overflow_test, config_test)
    #await tb.reset()
```

And it's failing on the await line (which probably wasn't commented out in the run you posted the link to).

If you look closely, you have a function and a class of the same name (SumN_tb). That's likely where your problem is coming from -- rename the function SumN_tb to e.g. `test_sum_n` and things should already look better.
