### ISSUE TITLE
Request to support data real for SV-RNM

### ISSUE THREAD

**Issue by mmatzev** [cocotb/cocotb#2833]
I tried to run a SV-RNM with verilator and cocotb  version 1.6.1.
It gave me a error message that the input data type float is not supported. It would be nice to support this.

A quick and dirty hack to a elif statement for float ended with an error about a exception in a coroutine.I don't know the internals of cocotb and do not understand how the value handling is really done. Therefore, I can't provide a patch. Sorry. 

Quick & dirty add in to handle.py:
![image](https://user-images.githubusercontent.com/6613334/150579423-0b52d3ab-2ace-4809-91ee-c017fd7de836.png)

Error message on debian WSL1:
![image](https://user-images.githubusercontent.com/6613334/150579516-146aef61-147d-49c8-9557-5802842c46ca.png)

**Comment by cmarqu** [comment]
Just quickly, https://github.com/cocotb/cocotb/pull/1282 says it should work. Might be a Verilator thing?

**Comment by ktbarrett** [comment]
Verilator has poor support for reals IIRC.

**Comment by ktbarrett** [comment]
Yes cocotb complains, but it complains because it thinks you are trying to set a real value on a logic or array of logic (ModifiableObject). This is due to Verilator reporting the actual type of the signal as `vpiReg` rather than a more descriptive type.

The patch works because the signal is actually a real under the hood, so the VPI call doesn't fail. However, allowing users to set reals on ModifiableObject in general may allow them to unsafely set reals on signals that aren't actually reals. This may fail politely or crash hard, depending on the simulator. We don't want to enable that kind of failure. It is better for Verilator to emit more expressive VPI types on signals.
