### ISSUE TITLE
cocotb-test: No module named 'cocotb._vendor.find_libpython'

### ISSUE THREAD

**Issue by nitheeshkm** [cocotb/cocotb#3131]
I recently updated my OS from Ubuntu 18.04 to Ubuntu 22.04 and started to see the iverilog vvp version errors which I was able to fix by downgrading to iverilog 10.3. But I'm stuck with the 'cocotb._vendor.find_libpython' noot found error.

Is there any way I can fix this? Please find log and version info below

### Version Info:
cocotb 1.7.2
Ubuntu 22.04 64-bit
iverlog 10.3
python 3.10.6

### log file (cleaned of proprietary information)
[errorlog.txt](https://github.com/cocotb/cocotb/files/10016847/errorlog.txt)

**Comment by imphil** [comment]
This is an issue in cocotb-test, not in cocotb itself. https://github.com/themperek/cocotb-test/blob/master/cocotb_test/simulator.py#L12 is importing a private dependency of cocotb, which went away with the 1.7.2 release.

@themperek Can you have a look and provide an updated version of cocotb-test?

**Comment by nitheeshkm** [comment]
Thank you @imphil. I was able to run the test by removing(commented out) the `import cocotb._vendor.find_libpython as find_libpython` and `self.env["LIBPYTHON_LOC"] = find_libpython.find_libpython()` from https://github.com/themperek/cocotb-test/blob/master/cocotb_test/simulator.py#L12. path /home/xunamex/.local/lib/python3.10/site-packages/cocotb_test/simulator.py

**Comment by imphil** [comment]
@nitheeshkm Since you're diving into this topic already, would you mind helping out solving the problem? To do so, open a pull request in the cocotb-test repository (https://github.com/themperek/cocotb-test/pulls) with a fix, which would be most likely two lines of code:

* Add a dependency to find_libpython to [setup.py](https://github.com/themperek/cocotb-test/blob/master/setup.py#L26)
* Modify cocotb_test/simulator.py to import `find_libpython` directly.

Here's how we did it on cocotb itself: https://github.com/cocotb/cocotb/commit/ea08c7facad6fac606e23c4cf93d26f94572570e. The required changes will be quite similar in cocotb-test.

If you've made to cocotb-test locally, install this version using "cd your/cocotb_test/directory; pip3 install -e ." and test if it actually works.

I'm looking forward to your contribution, and please reach out if anything is unclear. We're more than happy to help you get started.

**Comment by nitheeshkm** [comment]
@imphil, I was able to fix (&test) this based on your suggestions and ea08c7f. Created pull request here 
 https://github.com/themperek/cocotb-test/pull/206
