### ISSUE TITLE
Reading from 1-bit unpacked array w/ implicit pack dimension

### ISSUE THREAD

**Issue by scorbetta** [cocotb/cocotb#3448]
I'm running cocotb version 1.7.2 on a 64-bit Ubuntu 22.04 machine w/ Python 3.10.12. I'm using Verilator version 5.014 to run the simulations.

My SystemVerilog DUT:

```
module MY_MODULE #(
    parameter NUM_OUTPUTS = 2
)
(
    input CLK,
    output VALIDS [NUM_OUTPUTS]
);
```

and the Python test script contains the following readout:

```
# ...
flag = True
while flag:
    await FallingEdge(dut.CLK)
    fired = 0
    # num_outputs matches NUM_OUTPUTS parameter in design
    for odx in range(num_outputs):
        fired = fired + int(dut.VALIDS.value[odx])
    if fired == num_outputs:
        flag = False
```

Now, I have issues reading from `dut.VALIDS`, and I made some investigations on the way the `VALIDS` port is read as a function of its declaration.

**CASE#1: Implicit single-bit unpacked array**
With the above declaration, the following line always returns a string that is `NUM_OUTPUTS` bits long, but contains only **part** of the `VALIDS` array, in particular only `VALIDS[0]`. Other bits are set to 0:

```
print(f'{dut.VALIDS.value}')
```

I can show this comparing the output at screen with the VCD generated by the simulation.

**CASE#2: Explicit single-bit unpacked array**
With a slight change in the declaration as follows

```
module MY_MODULE #(
    parameter NUM_OUTPUTS = 2
)
(
    input CLK,
    output [0:0] VALIDS [NUM_OUTPUTS]
);
```

the same readout works as expected, and both the `VALIDS` bits (assume `NUM_OUTPUTS` equals 2) are read correctly.

**Comment by ktbarrett** [comment]
This is failing of `BinaryValue` and a failure to understand how to index signals in cocotb. The syntax that should be used to get a single bit from an unpackaed array is `dut.VALIDS[odx].value` (assuming Verilator can handle that). The reason it doesn't work is due to how `BinaryValue` handles indexing (very poorly). `BinaryValue` is going away and `LogicArray` is replacing it. You should be able to get the expected behavior using `LogicArray` by casting the `BinaryValue` before indexing it: `LogicArray(dut.VALIDS.value)[odx]` which should yield a `Logic` value.
