### ISSUE TITLE
conda or pip installable (enhancement request)

### ISSUE THREAD

**Issue by amal-khailtash** [cocotb/cocotb#440]
Make cocotb conda or pip installable package.  That would make it easy to install from conda repo or PyPI.

**Comment by jfosorio** [comment]
Conda would make cocotb so powerfull,  there is already a receipt for iverilog. With conda would be  posible to use numpy/scipy/ski-learn/jupyter. 
I would like to spent some time on it but find difficult to getting started.

**Comment by jeremyherbert** [comment]
I think the best thing would be to make it pip installable with wheels. Could probably do the wheel building automatically on appveyor and Travis, and it has the added bonus that Windows users won't have to individually go through the pain of installing toolchains. But this would also necessitate changing the build system to not be dependent on Make, otherwise Windows users will still have to go through that all. I'm not actually a Windows user, but I imagine in corporate environments it is quite common for HDL work.

This is something that I plan to work on when I get time, but I won't have any until the end of the year.

**Comment by pangloss** [comment]
+1

**Comment by elmsfu** [comment]
I see #517 has most of the work for pip. Also https://pypi.org/project/cocotb has a version of this from early 2017.

**Comment by themperek** [comment]
PyPI package is available now.
