### ISSUE TITLE
Python code not PEP8 compliant

### ISSUE THREAD

**Issue by chiggs** [cocotb/cocotb#6]
Should really conform to PEP8.

Significant area of discrepancy is lines > 79 characters

**Comment by ktbarrett** [comment]
@eric-wieser @cmarqu Are we decidedly not going for PEP8 support? From some of the comments on the linked issues, it seems that full PEP8 compliance is not wanted.

**Comment by eric-wieser** [comment]
I think if we're worried about line lengths we should focus our effort on the default log format!

I'm against running an autoformatter simply because it's not worth the churn, especially since most of that churn is for non-PEP8 rules.

There are definely bits in the flake8 ignore we can still clean up though.

**Comment by ktbarrett** [comment]
> I think if we're worried about line lengths we should focus our effort on the default log format!

Lol. 

> I'm against running an autoformatter simply because it's not worth the churn, especially since most of that churn is for non-PEP8 rules.

I agree. I think the code is already fairly readable, and if it isn't readable it's not because of formatting.

The flake8 issue will remain open, but if we aren't going for PEP8 at this point, this issue should be closed.
