### ISSUE TITLE
gitter room points to the wrong repo

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#986]
As discovered on gitter, the room is tied to the `OrionBytes/cocotb` repo (which does not exist).

The only way to fix this is for @chiggs or @OrionBytes to follow [the instructions on changing repo/org association](https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/rooms.md#change-room-security-after-creation), or to add someone else as an admin (perhaps @imphil) and have them follow those instructions.

Related: gh-529

**Comment by imphil** [comment]
I'm on it.

**Comment by OrionBytes** [comment]
Hi guys, sorry - I was not looking here (and in Gitter at all) for a long time. What should I do to solve issues with the room?
I can't find settings that I should use for that. The same in the official gitter client, It seems that I'm not admin of this room anymore. Or maybe I'm missing something?
@imphil what should I do?

Thanks!

**Comment by eric-wieser** [comment]
You need to talk to gitter support, there's no way to do it without their assistance

**Comment by imphil** [comment]
Please write an email to support@gitter.im with roughly the following content. Please CC me (mail@philipp-wagner.com):

---

Hi,

Could you please make the following changes to the room https://gitter.im/cocotb/Lobby:

- Link the room to https://github.com/cocotb/cocotb
- Make the user imphil admin in this room.

Background: I created this room some time ago for the cocotb community, and never linked it to the correct repository. Since then, the official repository has become https://github.com/cocotb/cocotb, and imphil is maintainer of cocotb (see https://github.com/cocotb/cocotb/blob/master/CONTRIBUTING.md#maintainers).

Thank you!

**Comment by OrionBytes** [comment]
I sent them email a little bit earlier today, so missed your proposition.
Here is info from support - 
>>
I have updated https://gitter.im/cocotb to be associated with the https://github.com/cocotb org tada. Anyone who is a member of that org, should be an admin.
If you still don't see admin permissions, run through these steps https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/faq.md#why-isnt-my-github-organisation-or-repos-appearing

**Comment by eric-wieser** [comment]
Looks like it's been associated with the org. Thanks @OrionBytes!

@imphil, as follow-up: It might be valuable to associate the room with the repo and not the org, since then issue links will work in chat.

**Comment by imphil** [comment]
It's all fixed now, enjoy!

**Comment by imphil** [comment]
Thanks @OrionBytes for getting in touch with the Gitter support.
